# Generated by Django 5.1.5 on 2025-01-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('trimester', models.CharField(choices=[('1', 'First Trimester'), ('2', 'Second Trimester'), ('3', 'Third Trimester')], max_length=1)),
            ],
        ),
    ]
