# Generated by Django 5.1.5 on 2025-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_exerciseplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('book_file', models.FileField(upload_to='books/')),
            ],
        ),
    ]
