# Generated by Django 5.1.5 on 2025-01-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_pregnancytip_babykickcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregnancytip',
            name='week',
        ),
    ]
