# Generated by Django 5.1.5 on 2025-01-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_remove_pregnancytip_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BabyKickCount',
        ),
    ]
