# Generated by Django 5.1.5 on 2025-01-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_babykickcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.CharField(choices=[('First', 'First Trimester'), ('Second', 'Second Trimester'), ('Third', 'Third Trimester')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meal_plan', models.TextField()),
                ('recommendations', models.TextField()),
            ],
            options={
                'ordering': ['trimester'],
            },
        ),
    ]
