# Generated by Django 5.1.5 on 2025-02-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0010_dietplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplan',
            name='trimester',
            field=models.CharField(choices=[('First', 'First Trimester'), ('Second', 'Second Trimester'), ('Third', 'Third Trimester')], max_length=50),
        ),
    ]
