# Generated by Django 5.1.5 on 2025-02-04 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0011_alter_exerciseplan_trimester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.userprofile'),
        ),
    ]
