# Generated by Django 5.1.7 on 2025-03-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0013_alter_dietplan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseYoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='exercise_yoga/')),
                ('trimester', models.IntegerField(choices=[(1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester'), (4, 'Postpartum')])),
            ],
        ),
    ]
